import { DocsBody, DocsDescription, DocsPage, DocsTitle } from "fumadocs-ui/page";
import { createRelativeLink } from "fumadocs-ui/mdx";
import { notFound } from "next/navigation";
import { CombinedAIButton } from "@/components/page-actions";
import { DocsPageFooter } from "@/components/docs-page-footer";
import {
  JsonLd,
  breadcrumbSchema,
  techArticleSchema,
} from "@/components/json-ld";
import { source } from "@/lib/source";
import { getMDXComponents } from "@/mdx-components";

const SECTION_LABELS: Record<string, string> = {
  integrations: "Integrate",
  packages: "API reference",
  conformance: "Conformance",
  spec: "AEO Spec v1.0",
  quickstart: "Get started",
  concepts: "Get started",
};

function buildBreadcrumb(slug: string[] | undefined, title: string) {
  const items = [
    { name: "Documentation", url: "/docs" },
  ];
  if (slug && slug.length > 1) {
    const sectionKey = slug[0];
    items.push({
      name: SECTION_LABELS[sectionKey] ?? sectionKey,
      url: `/docs/${sectionKey}`,
    });
  }
  if (slug && slug.length > 0) {
    items.push({ name: title, url: `/docs/${slug.join("/")}` });
  }
  return items;
}

export default async function Page(props: { params: Promise<{ slug?: string[] }> }) {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  const MDX = page.data.body;
  const filePath = page.file.path;
  const isAutoGenerated = filePath.startsWith("spec/");
  const githubUrl = isAutoGenerated
    ? `https://github.com/dodopayments/dualmark/tree/main/spec`
    : `https://github.com/dodopayments/dualmark/blob/main/apps/docs/content/docs/${filePath}`;
  const rawUrl = `/raw${page.url}`;

  const breadcrumbItems = buildBreadcrumb(params.slug, page.data.title);

  return (
    <DocsPage
      toc={page.data.toc}
      full={page.data.full}
      breadcrumb={{ includePage: true, includeSeparator: true }}
    >
      <JsonLd
        data={[
          techArticleSchema({
            title: page.data.title,
            description: page.data.description ?? "",
            url: page.url,
            section: SECTION_LABELS[params.slug?.[0] ?? ""] ?? "Documentation",
          }),
          breadcrumbSchema(breadcrumbItems),
        ]}
      />
      <DocsTitle className="flex flex-row items-start justify-between gap-4">
        <span>{page.data.title}</span>
        <div className="hidden shrink-0 md:block">
          <CombinedAIButton
            rawUrl={rawUrl}
            githubUrl={githubUrl}
            title={page.data.title}
          />
        </div>
      </DocsTitle>
      <DocsDescription>{page.data.description}</DocsDescription>
      <div className="mb-6 flex flex-row items-center gap-2 border-b border-[var(--color-border)] pb-6 md:hidden">
        <CombinedAIButton
          rawUrl={rawUrl}
          githubUrl={githubUrl}
          title={page.data.title}
        />
      </div>
      <DocsBody>
        <MDX components={getMDXComponents({ a: createRelativeLink(source, page) })} />
        <DocsPageFooter filePath={filePath} isAutoGenerated={isAutoGenerated} />
      </DocsBody>
    </DocsPage>
  );
}

export function generateStaticParams() {
  return source.generateParams();
}

export async function generateMetadata(props: { params: Promise<{ slug?: string[] }> }) {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) return {};
  const eyebrow = SECTION_LABELS[params.slug?.[0] ?? ""] ?? "Documentation";
  const ogParams = new URLSearchParams({
    title: page.data.title,
    eyebrow,
  });
  if (page.data.description) ogParams.set("description", page.data.description);
  const ogUrl = `/api/og?${ogParams.toString()}`;
  return {
    title: page.data.title,
    description: page.data.description,
    alternates: {
      canonical: page.url,
      types: {
        "text/markdown": `${page.url}.md`,
      },
    },
    openGraph: {
      title: page.data.title,
      description: page.data.description,
      url: page.url,
      type: "article",
      images: [{ url: ogUrl, width: 1200, height: 630, alt: page.data.title }],
    },
    twitter: {
      card: "summary_large_image",
      title: page.data.title,
      description: page.data.description,
      images: [ogUrl],
    },
  };
}
